// The executable icon is generated by tool/gen_app_icon.dart from the committed
// design/app-icon.png and committed itself, so these tests guard that the
// committed ICO is exactly what the generator produces from the master and
// that it carries the sizes Windows expects.
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:image/image.dart';

import '../tool/gen_app_icon.dart';

void main() {
  final master = decodePng(File(masterPath).readAsBytesSync())!;
  final ico = File(icoPath).readAsBytesSync();

  test('master is the approved 256x256 RGBA artwork', () {
    expect(master.width, 256);
    expect(master.height, 256);
    expect(master.hasAlpha, isTrue);
  });

  test('committed ICO is the deterministic build from the master', () {
    expect(ico, buildIco(master));
  });

  test('ICO decodes to the seven sizes, each square with alpha', () {
    // Independent of the generator's list: the sizes Windows must find.
    const expectedSizes = [16, 24, 32, 48, 64, 128, 256];
    expect(icoSizes, expectedSizes);

    final decoder = IcoDecoder();
    final info = decoder.startDecode(ico);

    expect(info, isNotNull, reason: '$icoPath must decode');
    expect(info!.numFrames, expectedSizes.length);

    final sizes = <int>[];
    for (var i = 0; i < info.numFrames; i++) {
      final frame = decoder.decodeFrame(i)!;
      expect(frame.width, frame.height, reason: 'frames must be square');
      expect(frame.hasAlpha, isTrue);
      sizes.add(frame.width);
    }
    expect(sizes..sort(), expectedSizes);
  });

  test('frames keep transparent corners, graphite tile and blue mark', () {
    final decoder = IcoDecoder()..startDecode(ico);
    // On the 256 canvas the bar spans y 64..96 and the legs end at y 192, with
    // a 16 px transparent tile margin; the same points scaled to each frame.
    for (var i = 0; i < icoSizes.length; i++) {
      final frame = decoder.decodeFrame(i)!;
      final s = frame.width / 256;
      final corner = frame.getPixel(0, 0);
      final bar = frame.getPixel((128 * s).floor(), (80 * s).floor());
      final tile = frame.getPixel((128 * s).floor(), (216 * s).floor());

      expect(corner.a, 0, reason: '${frame.width}px corner is transparent');
      expect(
        (bar.r, bar.g, bar.b, bar.a),
        (100, 181, 246, 255),
        reason: '${frame.width}px bar is #64B5F6',
      );
      expect(
        (tile.r, tile.g, tile.b, tile.a),
        (27, 27, 31, 255),
        reason: '${frame.width}px tile is #1B1B1F',
      );
    }
  });
}
