// The tray icons are generated by tool/gen_icons.dart and committed, so these
// tests guard the committed files, not the generator: the app loads them at
// runtime and a truncated or wrongly sized asset would only show up as a broken
// tray icon.
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:image/image.dart';

const _states = ['offline', 'idle', 'busy', 'compacting'];
const _icoSizes = [16, 20, 24, 32, 48, 64, 256];

void main() {
  for (final state in _states) {
    test('$state.png is a 256x256 image with a transparent background', () {
      final bytes = File('assets/tray/$state.png').readAsBytesSync();
      final png = decodePng(bytes);

      expect(png, isNotNull, reason: 'assets/tray/$state.png must decode');
      expect(png!.width, 256);
      expect(png.height, 256);
      expect(png.hasAlpha, isTrue);
      // Corner outside the disc is fully transparent, center fully opaque.
      expect(png.getPixel(0, 0).a, 0);
      expect(png.getPixel(128, 128).a, 255);
    });

    test('$state.ico holds every required size', () {
      final bytes = File('assets/tray/$state.ico').readAsBytesSync();
      final decoder = IcoDecoder();
      final info = decoder.startDecode(bytes);

      expect(info, isNotNull, reason: 'assets/tray/$state.ico must decode');
      expect(info!.numFrames, _icoSizes.length);

      final sizes = <int>[];
      for (var i = 0; i < info.numFrames; i++) {
        final frame = decoder.decodeFrame(i);
        expect(frame, isNotNull, reason: 'frame $i of $state.ico must decode');
        expect(frame!.width, frame.height, reason: 'frames must be square');
        expect(frame.hasAlpha, isTrue);
        sizes.add(frame.width);
      }
      expect(sizes..sort(), _icoSizes);
    });
  }

  test('the four states share one shape and differ only in color', () {
    final colors = {
      for (final state in _states)
        state: decodePng(File('assets/tray/$state.png').readAsBytesSync())!
            .getPixel(128, 128),
    };

    expect(
      colors.values.map((c) => '${c.r},${c.g},${c.b}').toSet(),
      hasLength(_states.length),
      reason: 'each state needs its own tray color',
    );
  });
}
